apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshoponwebapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshoponwebapi
  template:
    metadata:
      labels:
        app: eshoponwebapi
    spec:
      containers:
      - name: eshoponwebapi
        image: eshoponwebapi
        ports:
        - containerPort: 88

---

apiVersion: v1
kind: Service
metadata:
  name: eshoponwebapi
spec:
  selector:
    app: eshoponwebapi
  ports:
  - protocol: TCP
    port: 88

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller
spec:
  type: LoadBalancer
  selector:
    app: nginx-ingress
  ports:
  - name: http
    port: 88
    targetPort: http
  - name: https
    port: 4438
    targetPort: https
