apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: "AppDeploymentKV"
    userAssignedIdentityID: "/subscriptions/7085574e-de5f-47b0-8725-8f4abb74c8de/resourcegroups/Deploy/providers/Microsoft.ManagedIdentity/userAssignedIdentities/akskvmanagedid"
    objects: |
      array:
        - |
          objectName: dev-catalogdbconnstring
          objectType: secret
          objectVersion: ""
        - |
          objectName: dev-eshopIdentityConnString
          objectType: secret
          objectVersion: ""
    tenantId: "df01d38f-092c-4fd1-9115-46e922189958"

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshoponweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshoponweb
  template:
    metadata:
      labels:
        app: eshoponweb
    spec:
      containers:
      - name: eshoponweb
        image: eshoponweb
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        ports:
        - containerPort: 80
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
           secretProviderClass: "azure-kvname-user-msi"
---





---

apiVersion: v1
kind: Service
metadata:
  name: eshoponweb
spec:
  selector:
    app: eshoponweb
  ports:
  - protocol: TCP
    port: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller
spec:
  type: LoadBalancer
  selector:
    app: nginx-ingress
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https

---




#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: eshopweb-ingress-static
#  annotations:
#    nginx.ingress.kubernetes.io/ssl-redirect: "false"
#    nginx.ingress.kubernetes.io/rewrite-target: /static/$2
#spec:
#  type: LoadBalancer
#  ingressClassName: nginx
#  rules:
#  - http:
#      paths:
#      - path: /static(/|$)(.*)
#        pathType: Prefix
#        backend:
#          service:
#            name: eshopweb
#            port: 
#              number: 80