# Set PATH for dotnet tools
ENV PATH "$PATH:/home/$USERNAME/.dotnet/tools"

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["../eShopOnWeb.sln", "./"]
RUN dotnet restore "eShopOnWeb.sln"
COPY . .
WORKDIR "/src/."
RUN dotnet build "eShopOnWeb.sln" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "eShopOnWeb.sln" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "eShopOnWeb.dll"]

